<h1>Bibliotecas</h1>

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import statistics
from sqlalchemy import create_engine
import sqlalchemy
import schedule 
import time

<h1>Dataframe</h1>

In [2]:
#Buscando do Banco de Dados
engine  = sqlalchemy.create_engine('postgresql://postgres:sistema18@localhost:5432/transporte_db')
dfFinal = pd.read_sql_table("transporte",engine)

#Removendo valores igual a zero
df = dfFinal[(dfFinal[['velocidade']] != 0).all(axis=1)]

#removendo arquivos duplicados
dfboxplot=df.drop_duplicates()
dfboxplot

,ordem,linha,empresa,latitude,longitude,velocidade,horario,data
9,B10118,910,Transportes Paranapuan S/A,-22.84701,-43.24529,39,05:53:57,26/07/2022
11,C12025,2303,Expresso Recreio Ltda,-22.83768,-43.36507,24,06:02:21,26/07/2022
12,A41210,309,Real Auto Ônibus Ltda,-22.87395,-43.24175,6,06:21:43,26/07/2022
14,B28540,321,Viação Ideal S/A,-22.80028,-43.20290,16,06:45:55,26/07/2022
17,C30238,557,Transportes Futuro Ltda,-22.98760,-43.19560,25,07:21:07,26/07/2022
...,...,...,...,...,...,...,...,...
3564,B11646,363,Viação Vila Real S/A,-22.90198,-43.25344,39,10:14:00,26/07/2022
3566,B11533,908,Viação Vila Real S/A,-22.86765,-43.25749,12,10:14:01,26/07/2022
3567,B11546,908,Viação Vila Real S/A,-22.86800,-43.29743,14,10:14:01,26/07/2022
3569,B11612,300,Viação Vila Real S/A,-22.85878,-43.38092,53,10:14:01,26/07/2022
3570,B11633,363,Viação Vila Real S/A,-22.90612,-43.24309,28,10:14:01,26/07/2022

<h1>Info. Gerais Dataframe</h1>

In [3]:
#Informação referente ao tipo da variavel
dfboxplot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1899 entries, 9 to 3570
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ordem       1899 non-null   object
 1   linha       1899 non-null   object
 2   empresa     1899 non-null   object
 3   latitude    1899 non-null   float64
 4   longitude   1899 non-null   float64
 5   velocidade  1899 non-null   int64
 6   horario     1899 non-null   object
 7   data        1899 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 133.5+ KB

In [11]:
#Linhas de ônibus não duplicadas

dfboxplot['linha'].unique()

array(['910', '2303', '309', '321', '557', '795', '2336', '379', '292',
       '107', '2345', '350', '779', '840', '615', '639', '688', '685',
       '920', 'SV777', '565', '2803', '600', '711', '461', '861', '390',
       '369', '460', '621', '634', '623', '399', '774', '812', '2310',
       '913', '793', '805', '629', '323', '328', '554', '335', '759',
       '846', 'SVA665', '692', '343', '435', '801', '906', '752', '926',
       '853', '384', '539', '133', '770', '610', '342', 'SV774', '315',
       '483', '006', '2111', '329', '232', '2343', '371', '731', '497',
       '687', '426', '415', '919', '606', '790', '746', '361', '492',
       '918', '2114', '696', '455', '884', '324', '880', '247', '771',
       'SV779', '550', '397', '386', '627', '555', '393', 'LECD39', '362',
       '613', '756', '463', '210', '100', '584', '2335', '2342', '803',
       '409', '625', '908', '383', '616', '110', '355', '2381', '766',
       '721', '312', '348', '457', '327', '905', '862', '665', '878',
       'SP805', '306', '810', '863', '628', 'SP265', '112', '794', '892',
       '298', '474', 'SV394', '2334', 'SV474', '473', '866', '650', '275',
       'LECD42', '209', '917', '302', '485', '624', 'SV917', '2804',
       'LECD36', '108', '945', '553', '614', '2110', '202', '538', '472',
       '238', '608', 'SP513', '607', '410', '848', '217', '583', '638',
       '363', '422', '007', '2309', '870', '476', 'SP315', 'SP553',
       'SVB685', '775', '838', '867', '325', '691', '117', '951', '871',
       '864', '778', '652', '630', '897', '712', '2338', '804', '786',
       '883', '852', '220', '104', '835', 'SV866', '249', 'SV232', '893',
       '819', 'SV606', '821', '636', '950', '201', 'LECD44', '611', '847',
       '868', '900', '802', '2344', '313', 'SPA613', '851', '622', '2802',
       '954', '239', '953', '601', '388', '869', '341', '265', '326',
       '849', '783', '368', '552', '296', '378', '651', '936', '507',
       '743', '932', '2112', '433', '014', '837', '940', '895', '353',
       '548', 'LECD40', '741', 'LECD38', '843', 'SV790', '432', '836',
       '679', '603', '010', '925', '300', 'LECD49', '385', 'LECD50',
       '822', '745', 'LECD43', '859', '416', '349', '626'], dtype=object)

<h1>Critério de Análise</h1>

In [6]:
#O critério de contrução para o dataframe "Velocidade Por Linhas de ônibus",
#baseia-se na análise de variabilidade realizada através da interpretação
#da distância interquartílica entre os boxplots análisados. 

#Onde houver maior variabilidad mediante Linha Vs Velocidade, essas serão
#as escolhidas para serem estudadas.

#Desenvolvimento Boxplot

linha770 = []
linha920 = []
linha862 = [] 

linhas = ["770", "920", "862"]

for j, i in enumerate(dfboxplot.iloc[:, 1]):
    if i == linhas[0]:
        linha770.append(dfboxplot.iloc[j, 5])
    if i == linhas[1]:
        linha920.append(dfboxplot.iloc[j, 5])
    if i == linhas[2]:
        linha862.append(dfboxplot.iloc[j, 5])
dados_velocidade = [linha770, linha920, linha862]



# # Tamanho do gráfico em polegadas
# plt.figure(figsize =(11, 6))

# #Plotando o boxplot das espécies em relação ao tamanho das sépalas
# bplots = plt.boxplot(dados_velocidade,  vert = 1, patch_artist = False)

# colors = ['pink', 'lightblue', 'lightgreen']
# c = 0
# for i, bplot in enumerate(bplots['boxes']):
# bplot.set(color=colors[c], linewidth=3)
# c += 1

# # Linhas de contorno
# colorss = ['pink','pink', 'lightblue', 'lightblue', 'lightgreen', 'lightgreen']
# c2 = 0
# for whisker in bplots['whiskers']:
# whisker.set(color=colorss[c2], linewidth=3)
# c2+= 1

# c3 = 0
# for cap in bplots['caps']:
# cap.set(color=colorss[c3], linewidth=3)
# c3 +=1

# c4 = 0
# for median in bplots['medians']:
# median.set(color=colors[c4], linewidth=3)
# c4 +=1

# # Adicionando Título ao gráfico
# plt.title("Boxplot da base de dados Íris", loc="center", fontsize=18)
# plt.xlabel("Tipos de Flores")
# plt.ylabel("Comprimento das sépalas")

# plt.show()

<h1>Dataframe Velocidade Por Linhas de ônibus - LINHA 770</h1>

In [ ]:
linha7703=(dfFinal.loc[(dfFinal['linha']=="770") & (dfFinal['velocidade']!=0) & (dfFinal['data']=="18/07/2022"),['velocidade']])
L7703=linha7703.rename(columns={'velocidade':'Linha770'})

linha770=(dfFinal.loc[(dfFinal['linha']=="770") & (dfFinal['velocidade']!=0) & (dfFinal['data']=="19/07/2022"),['velocidade']])
L770=linha770.rename(columns={'velocidade':'Linha770'})

linha7702=(dfFinal.loc[(dfFinal['linha']=="770") & (dfFinal['velocidade']!=0) & (dfFinal['data']=="20/07/2022"),['velocidade']])
L7702=linha7702.rename(columns={'velocidade':'Linha770'})


linha7704=(dfFinal.loc[(dfFinal['linha']=="770") & (dfFinal['velocidade']!=0) & (dfFinal['data']=="21/07/2022"),['velocidade']])
L7704=linha7704.rename(columns={'velocidade':'Linha770'})

linha7705=(dfFinal.loc[(dfFinal['linha']=="770") & (dfFinal['velocidade']!=0) & (dfFinal['data']=="22/07/2022"),['velocidade']])
L7705=linha7705.rename(columns={'velocidade':'Linha770'})

linha7706=(dfFinal.loc[(dfFinal['linha']=="770") & (dfFinal['velocidade']!=0) & (dfFinal['data']=="23/07/2022"),['velocidade']])
L7706=linha7706.rename(columns={'velocidade':'Linha770'})




#Conversão dos Filtros para lista

X1=L770['Linha770'].tolist()
X2=L7702['Linha770'].tolist()
X3=L7703['Linha770'].tolist()
X4=L7704['Linha770'].tolist()
X5=L7705['Linha770'].tolist()
X6=L7706['Linha770'].tolist()

#Dataframe Velocidade
df1 = pd.DataFrame({
    'LINHA770 - 18/07/2022 ': pd.Series(X3,dtype='float64'),
    'LINHA770 - 19/07/2022 ': pd.Series(X1,dtype='float64'),
    'LINHA770 - 20/07/2022 ': pd.Series(X2,dtype='float64'),
    'LINHA770 - 21/07/2022 ': pd.Series(X4,dtype='float64'),
    'LINHA770 - 22/07/2022 ': pd.Series(X5,dtype='float64'),
    'LINHA770 - 23/07/2022 ': pd.Series(X6,dtype='float64')
})



df_velocidade_linhas=df1.replace(np.nan,0)
df_ajustado=df_velocidade_linhas.T
df_ajustado

<h1> CEP - Velocidade em relação as linhas de Ônibus Gráfico </h1>

In [ ]:

x = np.array(df_ajustado[[0,1,2,3,4]])

# Define list variable for groups means
x_bar = []

# Define list variable for groups ranges
r = [] 

# Get and append groups means and ranges
for group in x:
    x_bar.append(group.mean())
    r.append(group.max() - group.min())
    
# Plot x-bar and R charts
fig, axs = plt.subplots(2, figsize=(15,15))

# x-bar chart

axs[0].plot(x_bar, linestyle='-', marker='o', color='black')
axs[0].axhline((statistics.mean(x_bar)+0.577*statistics.mean(r)), color='red', linestyle='dashed')
axs[0].axhline((statistics.mean(x_bar)-0.577*statistics.mean(r)), color='red', linestyle='dashed')
axs[0].axhline((statistics.mean(x_bar)), color='blue')
axs[0].set_title('Gráfico X-Barra')
axs[0].set(xlabel='Group', ylabel='Mean')

# R chart
axs[1].plot(r, linestyle='-', marker='o', color='black')
axs[1].axhline((2.574*statistics.mean(r)), color='red', linestyle='dashed')
axs[1].axhline((0*statistics.mean(r)), color='red', linestyle='dashed')
axs[1].axhline((statistics.mean(r)), color='blue')
axs[1].set_ylim(bottom=0)
axs[1].set_title('Gráfico R ')
axs[1].set(xlabel='Group', ylabel='Range')

# Validate points out of control limits for x-bar chart
i = 0
control = True
for group in x_bar:
    if group > statistics.mean(x_bar)+0.577*statistics.mean(r) or group < statistics.mean(x_bar)-0.577*statistics.mean(r):
        print('Group', i, 'out of mean control limits!')
        control = False
    i += 1
if control == True:
    print('All points within control limits.')
    
# Validate points out of control limits for R chart
i = 0
control = True
for group in r:
    if group > 2.574*statistics.mean(r):
        print('Group', i, 'out of range cotrol limits!')
        control = False
    i += 1
if control == True:
    print('All points within control limits.')